[package.metadata.generate-rpm]

name = "rustcfml"
summary = "High-performance CFML runtime"
license = "MIT"

assets = [
    { source = "target/release/rustcfml", dest = "/usr/bin/rustcfml", mode = "755" }
]

[package.metadata.generate-rpm.requires]

glibc = ">= 2.34"
