//! Declared metadata about built-in functions — the SINGLE enumerable source of
//! truth for "what is a builtin" and "which builtins are VM-intercepted".
//!
//! # Why this exists
//! `CfmlVirtualMachine::call_function` grew to **7,496 lines (20% of `cfml-vm/src/lib.rs`)**
//! because the documented recipe for adding a VM-intercepted builtin was "append a
//! `name_lower == "..."` branch to it", and nothing ever removed one. Cross-cutting
//! concerns (`sandbox_intercept`, `s3_intercept`, `resolve_file_bif_paths`) were then
//! woven into the same chain, so the question *"is this name intercepted?"* became
//! unanswerable without executing the function. That blocked compile-time BIF binding —
//! a wrong answer does not merely run slow, it **silently bypasses the sandbox**.
//!
//! Lucee does the opposite: it DECLARES its BIFs (`FunctionLibFunction` carries the
//! implementing class and argument types, read at compile time). Declarations stay
//! enumerable; chains do not. This module is that declaration.
//!
//! # The closing mechanism (the part that matters)
//! Both lists are guarded by tests that check them against reality, so they cannot drift:
//!   * `cfml-stdlib` asserts [`BUILTIN_NAMES`] equals the registration table exactly.
//!   * `cfml-vm` scans `call_function` and asserts every name it compares against is in
//!     [`VM_INTERCEPTED`].
//! Appending an intercept without declaring it therefore FAILS THE BUILD. Without that
//! guard these lists would rot exactly like the chain they replace.
//!
//! # Safety asymmetry — read before editing
//! **Over-declaring an intercept is safe** (the name simply is not compile-time bound, so
//! it keeps the old dispatch). **Under-declaring is not** (interception is skipped). When
//! in doubt, declare it intercepted.

/// Every name registered by `cfml_stdlib::builtins::get_builtin_functions()`, lowercased
/// and sorted. Guarded by a test in `cfml-stdlib`.
pub const BUILTIN_NAMES: &[&str] = &[
    "$siobroadcast", "$siodisconnect", "$siogetdata", "$siojoinroom",
    "$sioleaveallrooms", "$sioleaveroom", "$sioregisterednamespaces", "$sioregisternamespace",
    "$sioregisternshandler", "$sioregistersockethandler", "$siosend", "$siosetdata",
    "$siosocketcount", "__cfabort", "__cfapplication", "__cfcache",
    "__cfcontent", "__cfcookie", "__cfexecute", "__cfexit",
    "__cffile_upload", "__cfheader", "__cfhtmlbody", "__cfhtmlhead",
    "__cfinvoke", "__cflocation", "__cflock_end", "__cflock_start",
    "__cflog", "__cfloginuser", "__cflogout", "__cfloop_file_lines",
    "__cfmail", "__cfparam", "__cfparam_validate", "__cfprocessingdirective_collapse",
    "__cfsavecontent_end", "__cfsavecontent_start", "__cfsetting", "__cfthread_join",
    "__cfthread_run", "__cfthread_terminate", "__cftransaction_commit", "__cftransaction_end",
    "__cftransaction_rollback", "__cftransaction_start", "__dbinfo_impl", "__jsonschemavalidateresult",
    "__querysetrow", "__register_ds_timeout", "__writetext", "_schedule",
    "abs", "acos", "applicationstop", "argon2checkhash",
    "arrayappend", "arrayavg", "arrayclear", "arraycontains",
    "arraycontainsnocase", "arraydelete", "arraydeleteat", "arraydeletenocase",
    "arrayeach", "arrayevery", "arrayfilter", "arrayfind",
    "arrayfindall", "arrayfindallnocase", "arrayfindnocase", "arrayfirst",
    "arrayindexexists", "arrayinsertat", "arrayisdefined", "arrayisempty",
    "arraylast", "arraylen", "arraymap", "arraymax",
    "arraymedian", "arraymerge", "arraymid", "arraymin",
    "arraynew", "arraypop", "arrayprepend", "arraypush",
    "arrayrange", "arrayreduce", "arrayreduceright", "arrayresize",
    "arrayreverse", "arrayset", "arrayshift", "arrayslice",
    "arraysome", "arraysort", "arraysplice", "arraysum",
    "arrayswap", "arraytolist", "arraytostruct", "arrayunshift",
    "asc", "asin", "assertbroadcast", "atan",
    "bcrypthash", "bcryptverify", "binarydecode", "binaryencode",
    "bitand", "bitmaskclear", "bitmaskread", "bitmaskset",
    "bitnot", "bitor", "bitshln", "bitshrn",
    "bitxor", "booleanformat", "cacheclear", "cachecount",
    "cachedelete", "cacheget", "cachegetall", "cachegetallids",
    "cachegetproperties", "cachekeyexists", "cacheput", "canonicalize",
    "ceiling", "cfdbinfo", "cfdirectory", "cfdump",
    "cffile", "cfhttp", "cfimage", "cfzip",
    "charsetdecode", "charsetencode", "chr", "cjustify",
    "collectioneach", "collectionevery", "collectionfilter", "collectionmap",
    "collectionreduce", "collectionsome", "compare", "comparenocase",
    "cos", "createdate", "createdatetime", "createdynamicproxy",
    "createguid", "createobject", "createodbcdate", "createodbcdatetime",
    "csvformatrow",
    "createodbctime", "createtime", "createtimespan", "createuniqueid",
    "createuuid", "csrfgeneratetoken", "csrfverifytoken", "dateadd",
    "datecompare", "dateconvert", "datediff", "dateformat",
    "datepart", "datetimeformat", "day", "dayofweek",
    "dayofweekasstring", "dayofweekshortasstring", "dayofyear", "daysinmonth",
    "daysinyear", "dbinfo", "de", "debugadd",
    "decimalformat", "decodeforhtml", "decodefromurl", "decrementvalue",
    "decrypt", "deserializejson", "directorycopy", "directorycreate",
    "directorydelete", "directoryexists", "directorylist", "directoryrename",
    "dollarformat", "dump", "duplicate", "each",
    "echo", "encodefor", "encodeforcss", "encodeforhtml",
    "encodeforhtmlattribute", "encodeforjavascript", "encodeforurl", "encodeforxml",
    "encodeforxmlattribute", "encrypt", "evaluate", "exceptionkeyexists",
    "exp", "expandpath", "fileappend", "fileclose",
    "filecopy", "filedelete", "fileexists", "filegetmimetype",
    "fileiseof", "filemove", "fileopen", "fileread",
    "filereadbinary", "filereadline", "filesetaccessmode", "filesetattribute",
    "filesetlastmodified", "fileupload", "fileuploadall", "filewrite",
    "filewriteline", "find", "findnocase", "findoneof",
    "firstdayofmonth", "fix", "floor", "formatbasen",
    "generateargon2hash", "generatebcrypthash", "generatepbkdfkey", "generatescrypthash",
    "generatesecretkey", "getapplicationmetadata", "getapplicationsettings", "getauthuser",
    "getbasetagdata", "getbasetaglist", "getbasetemplatepath", "getcanonicalpath",
    "getcomponentmetadata", "getcomponentstaticscope", "getcontextroot", "getcurrenttemplatepath",
    "getdebugdata", "getdirectoryfrompath", "getenvironmentvariable", "getfilefrompath",
    "getfileinfo", "getfunctioncalledname", "getfunctionlist", "gethttprequestdata",
    "gethttptimestring", "getlocale", "getmetadata", "getnumericdate",
    "getpagecontext", "getprofilesections", "getprofilestring", "getreadableimageformats",
    "getrequestprofile", "gettagdata", "gettempdirectory", "gettempfile",
    "gettemplatepath", "gettickcount", "gettimezone", "gettimezoneinfo",
    "gettoken", "getvariable", "getwriteableimageformats", "hash",
    "hmac", "hour", "htmlcodeformat", "htmleditformat",
    "htmldocument", "htmlparse", "iif", "imageaddborder", "imageblur",
    "imageclearrect", "imagecopy", "imagecrop", "imagedrawarc",
    "imagedrawbeveledrect", "imagedrawcubiccurve", "imagedrawimage", "imagedrawline",
    "imagedrawlines", "imagedrawoval", "imagedrawpoint", "imagedrawquadraticcurve",
    "imagedrawrect", "imagedrawroundrect", "imagedrawtext", "imageflip",
    "imagegetblob", "imagegetbufferedimage", "imagegetexifmetadata", "imagegetexiftag",
    "imagegetheight", "imagegetiptcmetadata", "imagegetiptctag", "imagegetwidth",
    "imagegrayscale", "imageinfo", "imagemakecolortransparent", "imagemaketranslucent",
    "imagenegative", "imagenew", "imageoverlay", "imagepaste",
    "imageread", "imagereadbase64", "imageresize", "imagerotate",
    "imagerotatedrawingaxis", "imagescaletofit", "imagesetantialiasing", "imagesetbackgroundcolor",
    "imagesetdrawingcolor", "imagesetdrawingstroke", "imagesetdrawingtransparency", "imagesharpen",
    "imageshear", "imagesheardrawingaxis", "imagetranslate", "imagetranslatedrawingaxis",
    "imagewrite", "imagewritebase64", "imagexordrawingmode", "incrementvalue",
    "inputbasen", "insert", "int", "invoke",
    "io", "isarray", "isbinary", "isboolean",
    "isclosure", "iscustomfunction", "isdate", "isdebugmode",
    "isdefined", "isempty", "isimage", "isimagefile",
    "isinstanceof", "isinthread", "isjson", "isleapyear",
    "isnull", "isnumeric", "isobject", "isquery",
    "issimplevalue", "isspreadsheetfile", "isspreadsheetobject", "isstruct",
    "isuserinrole", "isuserloggedin", "isvalid", "isxml",
    "isxmlattribute", "isxmldoc", "isxmlelem", "isxmlnode",
    "isxmlroot", "javacast", "jsstringformat", "jwtdecode",
    "jwtsign", "jwtverify", "lcase", "left",
    "len", "listappend", "listavg", "listchangedelims",
    "listcompact", "listcontains", "listcontainsnocase", "listdeleteat",
    "listeach", "listevery", "listfilter", "listfind",
    "listfindnocase", "listfirst", "listgetat", "listindexexists",
    "listinsertat", "listitemtrim", "listlast", "listlen",
    "listmap", "listnew", "listprepend", "listqualify",
    "listreduce", "listreduceright", "listremoveduplicates", "listrest",
    "listsetat", "listsome", "listsort", "listtoarray",
    "listvaluecount", "listvaluecountnocase", "ljustify", "log",
    "log10", "lscurrencyformat", "lsdateformat", "lsdatetimeformat",
    "lsdayofweek", "lseurocurrencyformat", "lsiscurrency", "lsisdate",
    "lsisnumeric", "lsnumberformat", "lsparsecurrency", "lsparsedatetime",
    "lsparsenumber", "lstimeformat", "lsweek", "ltrim",
    "max", "metaphone", "mid", "millisecond",
    "min", "minute", "month", "monthasstring",
    "monthshortasstring", "newline", "now", "nowserver",
    "nullvalue", "numberformat", "objectload", "objectsave",
    "paragraphformat", "parsedatetime", "pi", "pow",
    "preservesinglequotes", "profilenow", "quarter", "queryaddcolumn",
    "queryaddrow", "queryappend", "querycolumnarray", "querycolumncount",
    "querycolumndata", "querycolumnexists", "querycolumnlist", "querycurrentrow",
    "querydeletecolumn", "querydeleterow", "queryeach", "queryevery",
    "queryexecute", "queryfilter", "querygetcell", "querygetresult",
    "querygetrow", "queryinsertat", "querykeyexists", "querymap",
    "querynew", "queryprepend", "queryrecordcount", "queryreduce",
    "queryregisterfunction", "queryreverse", "queryrowdata", "queryrowswap",
    "querysetcell", "querysetrow", "queryslice", "querysome",
    "querysort", "quotedvaluelist", "rand", "randombytes",
    "randomize", "randrange", "readline", "reescape", "refind",
    "refindnocase", "rematch", "rematchnocase", "removechars",
    "repeatstring", "replace", "replacelist", "replacelistnocase",
    "replacenocase", "rereplace", "rereplacenocase", "reverse",
    "right", "rjustify", "round", "rtrim",
    "runasync", "s3clearbucket", "s3copy", "s3createbucket",
    "s3delete", "s3download", "s3exists", "s3generatepresignedurl",
    "s3generateuri", "s3getmetadata", "s3listbucket", "s3listbuckets",
    "s3move", "s3read", "s3readbinary", "s3upload",
    "s3write", "sanitizehtml", "second", "serialize",
    "serializejson", "sessioncommit", "sessiongetmetadata", "sessioninvalidate",
    "sessionrotate", "setencoding", "setlocale", "setprofilestring",
    "settimezone", "setvariable", "sgn", "sin",
    "sleep", "smtpconnectiontest", "soundex", "spanexcluding", "spanincluding",
    "spreadsheet", "spreadsheetautosizecolumn", "spreadsheetaddautofilter", "spreadsheetaddchart", "spreadsheetaddcolumn",
    "spreadsheetaddconditionalformatting", "spreadsheetadddatavalidation", "spreadsheetaddfreezepane", "spreadsheetaddimage",
    "spreadsheetaddinfo", "spreadsheetaddpagebreaks", "spreadsheetaddrow", "spreadsheetaddrows",
    "spreadsheetaddsplitpane", "spreadsheetclearcell", "spreadsheetclearcellrange", "spreadsheetcreatesheet",
    "spreadsheetdeletecolumn", "spreadsheetdeletecolumns", "spreadsheetdeleterow", "spreadsheetdeleterows",
    "spreadsheetformatcell", "spreadsheetformatcellrange", "spreadsheetformatcolumn", "spreadsheetformatrow",
    "spreadsheetfromjson", "spreadsheetgetcellcomment", "spreadsheetgetcellformat", "spreadsheetgetcellformula",
    "spreadsheetgetcellhyperlink", "spreadsheetgetcelltype", "spreadsheetgetcellvalue", "spreadsheetgetcolumncount",
    "spreadsheetgetcolumnwidth", "spreadsheetinfo", "spreadsheetmergecells", "spreadsheetnew",
    "spreadsheetread", "spreadsheetreadbinary", "spreadsheetreadcsv", "spreadsheetrenamesheet",
    "spreadsheetsetactivecell", "spreadsheetsetactivesheet", "spreadsheetsetactivesheetnumber", "spreadsheetsetcellcomment",
    "spreadsheetsetcellformula", "spreadsheetsetcellhyperlink", "spreadsheetsetcellrangevalue", "spreadsheetsetcellvalue",
    "spreadsheetsetcolumnhidden", "spreadsheetsetcolumnwidth", "spreadsheetsetfittopage", "spreadsheetsetfooter",
    "spreadsheetsetheader", "spreadsheetsetprintorientation", "spreadsheetsetrepeatingcolumns", "spreadsheetsetrepeatingrows",
    "spreadsheetsetrowheight", "spreadsheetsetrowhidden", "spreadsheetshiftcolumns", "spreadsheetshiftrows",
    "spreadsheettoarray", "spreadsheettocsv", "spreadsheettojson", "spreadsheettoquery",
    "spreadsheetwrite", "spreadsheetwritetocsv", "sqr", "sqrt",
    "storegetmetadata", "stringeach", "stringevery", "stringfilter",
    "stringmap", "stringreduce", "stringsome", "stringsort",
    "stripcr", "structappend", "structclear", "structcopy",
    "structcount", "structdelete", "structeach", "structequals",
    "structevery", "structfilter", "structfind", "structfindkey",
    "structfindvalue", "structget", "structgetmetadata", "structinsert",
    "structiscasesensitive", "structisempty", "structisordered", "structkeyarray",
    "structkeyexists", "structkeylist", "structkeytranslate", "structmap",
    "structnew", "structreduce", "structsetmetadata", "structsome",
    "structsort", "structtoquerystring", "structtosorted", "structupdate",
    "structvaluearray", "systemcacheclear", "systemoutput", "tan",
    "threadjoin", "threadterminate", "throw", "timeformat",
    "tobase64", "tobinary", "toboolean", "tonumeric",
    "toscript", "tostring", "trace", "trim",
    "truefalseformat", "ucase", "ucfirst", "urldecode",
    "urlencode", "urlencodedformat", "val", "validatejson",
    "valuearray", "valuelist", "verifybcrypthash", "verifyscrypthash",
    "week", "wrap", "writedump", "writelog",
    "writeoutput", "wspresence", "wspublish", "wssubscribe",
    "wsunsubscribe", "xmlchildpos", "xmlelemnew", "xmlformat",
    "xmlgetnodetype", "xmlhaschild", "xmlnew", "xmlparse",
    "xmlsearch", "xmltransform", "xmlvalidate", "xmpparse",
    "yamldeserialize", "yamldeserializefile", "yamlserialize", "year",
    "yesnoformat",
];

/// Every name `call_function` dispatches on before reaching the generic builtin path,
/// lowercased and sorted. Includes internal `__`-prefixed tag helpers that are not
/// registered builtins. Guarded by a source-scanning test in `cfml-vm`.
pub const VM_INTERCEPTED: &[&str] = &[
    "$siobroadcast", "$siodisconnect", "$siogetdata", "$siojoinroom",
    "$sioleaveallrooms", "$sioleaveroom", "$sioregisterednamespaces", "$sioregisternamespace",
    "$sioregisternshandler", "$sioregistersockethandler", "$siosend", "$siosetdata",
    "$siosocketcount", "__cfabort", "__cfapplication", "__cfcache",
    "__cfcontent", "__cfcookie", "__cfcustomtag", "__cfcustomtag_end",
    "__cfcustomtag_start", "__cfdirectory", "__cfdocument", "__cfdump",
    "__cfexecute", "__cfexit", "__cffile_upload", "__cfheader",
    "__cfhtmlbody", "__cfhtmlhead", "__cfhttp", "__cfinvoke",
    "__cflocation", "__cflock_end", "__cflock_start", "__cflog",
    "__cfloginuser", "__cflogout", "__cfloop_file_lines", "__cfmodule",
    "__cfparam", "__cfsavecontent_end", "__cfsavecontent_start", "__cfsetting",
    "__cfspreadsheet", "__cfthread_join", "__cfthread_run", "__cfthread_terminate",
    "__cftransaction_commit", "__cftransaction_end", "__cftransaction_rollback", "__cftransaction_start",
    "__variables", "__writetext", "_schedule", "abort",
    "application", "applicationstop", "arguments", "array",
    "arraycontains", "arraydelete", "arraydeletenocase", "arrayeach",
    "arrayevery", "arrayfilter", "arrayfind", "arrayfindall",
    "arrayfindallnocase",
    "arrayfindnocase", "arraymap", "arrayreduce", "arraysome",
    "arraysort", "assertbroadcast", "attributes", "bcrypt",
    "cacheclear", "cachecount", "cachedelete", "cacheget",
    "cachegetall", "cachegetallids", "cachegetproperties", "cachekeyexists",
    "cacheput", "callstackdump", "callstackget", "cfabort",
    "cfcache", "cfcatch", "cfcontent", "cfcookie",
    "cfdbinfo", "cfdirectory", "cfdocument", "cfdump",
    "cfexecute", "cffile", "cfheader", "cfhtmlbody",
    "cfhtmlhead", "cfhttp", "cfinvoke", "cflocation",
    "cflog", "cfmodule", "cfpdf", "cfsetting",
    "cfspreadsheet", "cfzip", "cgi", "client",
    "collectioneach", "collectionevery", "collectionfilter", "collectionmap",
    "collectionreduce", "collectionsome", "component", "cookie",
    "createdynamicproxy", "createobject", "csrfgeneratetoken", "csrfverifytoken",
    "dateconvert", "dbinfo", "debugadd", "delete",
    "directory", "directorycopy", "directorycreate", "directorydelete",
    "directoryexists", "directorylist", "directoryrename", "dump",
    "each", "echo", "evaluate", "expand",
    "expandpath", "false", "file", "fileappend",
    "filecopy", "filedelete", "fileexists", "filemove",
    "fileopen", "fileread", "filereadbinary", "filesetaccessmode",
    "filesetattribute", "filesetlastmodified", "fileupload", "fileuploadall",
    "filewrite", "filewriteline", "form", "getapplicationmetadata",
    "getapplicationsettings", "getauthuser", "getbasetagdata", "getbasetaglist",
    "getbasetemplatepath", "getcomponentmetadata", "getcomponentstaticscope", "getcurrenttemplatepath",
    "getdebugdata", "getfileinfo", "getfunctioncalledname", "gethttprequestdata",
    "getlocale", "getmetadata", "getpagecontext", "getprofilesections",
    "getprofilestring", "getrequestprofile", "gettimezone", "gettimezoneinfo",
    "getvariable", "html", "image", "invoke",
    "io", "isdebugmode", "isdefined", "isinthread",
    "isuserinrole", "isuserloggedin", "json", "label",
    "listeach", "listevery", "listfilter", "listmap",
    "listreduce", "listreduceright", "listsome", "local",
    "local2utc", "location", "name", "no",
    "numeric", "output", "precisionevaluate", "profilenow",
    "queryaddrow", "queryappend", "queryeach", "queryevery",
    "queryexecute", "queryfilter", "querymap", "queryreduce",
    "queryregisterfunction", "querysetcell", "querysetrow", "querysome",
    "querysort", "request", "runasync", "sanitizehtml",
    "server", "session", "sessioncommit", "sessiongetmetadata",
    "sessioninvalidate", "sessionrotate", "setencoding", "setlocale",
    "setprofilestring", "settimezone", "setvariable", "sleep",
    "spreadsheetwrite", "static", "string", "stringeach",
    "stringevery", "stringfilter", "stringmap", "stringreduce",
    "stringsome", "stringsort", "structeach", "structevery",
    "structfilter", "structget", "structmap", "structreduce",
    "structsome",
    "this", "thread", "threadjoin", "threadterminate",
    "throw", "top", "trace", "true",
    "url", "utc2local", "var", "variables",
    "writedump", "writelog", "writeoutput", "wspresence",
    "wspublish", "wssubscribe", "wsunsubscribe", "yes",
];

/// True if `lower` (already lowercased) is dispatched by the VM before the generic
/// builtin path, and therefore must NOT be compile-time bound.
///
/// The `$sio` family is matched by PREFIX in the chain (`name_lower.starts_with("$sio")`),
/// so it is handled as a prefix here rather than enumerated.
#[inline]
pub fn is_vm_intercepted(lower: &str) -> bool {
    lower.starts_with("$sio") || VM_INTERCEPTED.binary_search(&lower).is_ok()
}

/// True if `lower` is a registered builtin that the VM does NOT intercept — i.e. it is
/// safe for codegen to bind at compile time.
#[inline]
pub fn is_pure_builtin(lower: &str) -> bool {
    BUILTIN_NAMES.binary_search(&lower).is_ok() && !is_vm_intercepted(lower)
}
