#!/usr/bin/env python3
"""Size the per-op penalty of an UNSLOTTED frame — the next action from the
Part 1 verdict (PERFORMANCE_ROADMAP).

66% of frame entries in a warm Preside render (5,425 of 8,216) run unslotted,
and the Part 1 reconciliation showed the same op costs ~5.3x more inside a real
frame than in a tight loop. This asks how much of that multiplier is slotting.

⚠️ This is NOT the v0.586 "slot-coverage widening" measurement, which was DEAD.
That one counted which FUNCTIONS were disqualified and asked whether more could
be admitted. This one holds the function fixed and asks what an unslotted ENTRY
costs PER OP. Different question, different answer possible.

The A/B: identical function bodies, identical op streams at runtime, differing
only in a `if ( false ) { evaluate( "1" ); }` branch. The codegen slot-admission
scan (compiler.rs, REFLECTIVE_BUILTINS) walks the WHOLE instruction list and
disqualifies the function on sight of a `LoadGlobal(evaluate)`, so the branch
costs nothing at runtime (never taken) while flipping the frame to unslotted.
That makes slotting the only variable.

WIDTH is swept because the hypothesis is that unslotted cost scales with the
locals map: a slot read is an array index, a by-name read is a hash probe into
a map that a real Preside frame fills far past what a microbench builds.

Run with --no-jit: Preside admits ~0% and the JIT would compile these.
"""

WIDTHS = [1, 4, 8, 16, 32, 64]
READS_PER_ITER = 8

HEAD = '''<cfsetting showdebugoutput="false">
<cfscript>
/*
 * GENERATED by scripts/perf/gen_slotbench.py -- edit the generator.
 *
 * Per-op penalty of an UNSLOTTED frame. Each pair of functions below has an
 * IDENTICAL body and an identical runtime op stream; the `_unslotted` twin
 * carries `if ( false ) { evaluate( "1" ); }`, which the codegen slot-admission
 * scan sees statically and which never executes. So the measured difference is
 * slot-indexed local access vs by-name local access, and nothing else.
 *
 * URL params: ?iters=N &passes=N &warmups=N
 */
'''

FN_SLOTTED = '''
function c_slotted_{w}( n ) {{
    var acc = 0;
{decls}
    for ( var i = 0; i < n; i++ ) {{
        acc += {reads};
    }}
    return acc;
}}
'''

FN_UNSLOTTED = '''
function c_unslotted_{w}( n ) {{
    var acc = 0;
{decls}
    // Never executes. Disqualifies the frame from slots at COMPILE time only.
    if ( false ) {{ evaluate( "1" ); }}
    for ( var i = 0; i < n; i++ ) {{
        acc += {reads};
    }}
    return acc;
}}
'''

TAIL = '''
function timeCase( fn, n, warmups, passes ) {
    var best = 0;
    var acc  = 0;
    for ( var p = 1; p <= warmups + passes; p++ ) {
        var t0 = getTickCount( "nano" );
        acc += fn( n );
        var el = getTickCount( "nano" ) - t0;
        if ( p > warmups && ( best == 0 || el < best ) ) { best = el; }
    }
    return { ns = best / n, acc = acc };
}

iters   = val( url.iters   ?: 300000 );
passes  = val( url.passes  ?: 4 );
warmups = val( url.warmups ?: 3 );
sink    = 0;
reads   = __READS__;

writeOutput( "PORT=" & cgi.server_port & chr(10) );
writeOutput( "ITERS=" & iters & " PASSES=" & passes & " WARMUPS=" & warmups
           & " READS_PER_ITER=" & reads & chr(10) );
writeOutput( "WIDTH" & chr(9) & "SLOTTED_NS" & chr(9) & "UNSLOTTED_NS"
           & chr(9) & "DELTA_NS" & chr(9) & "DELTA_PER_READ" & chr(10) );

widths = [ __WIDTHS__ ];
slotFns   = [ __SLOTFNS__ ];
unslotFns = [ __UNSLOTFNS__ ];

for ( wi = 1; wi <= arrayLen( widths ); wi++ ) {
    s = timeCase( slotFns[ wi ],   iters, warmups, passes );
    u = timeCase( unslotFns[ wi ], iters, warmups, passes );
    sink += s.acc + u.acc;
    d = u.ns - s.ns;
    writeOutput( widths[ wi ] & chr(9) & numberFormat( s.ns, "0.000" )
               & chr(9) & numberFormat( u.ns, "0.000" )
               & chr(9) & numberFormat( d, "0.000" )
               & chr(9) & numberFormat( d / reads, "0.000" ) & chr(10) );
}
writeOutput( "SINK=" & sink & chr(10) );
</cfscript>
'''


def main():
    import sys
    out = [HEAD]
    for w in WIDTHS:
        # `w` locals declared; the loop reads the first READS_PER_ITER of them
        # (cycling if the frame is narrower), so the READ COUNT is constant
        # across widths and only the map WIDTH varies.
        decls = "\n".join(
            "    var v%d = %d;" % (k, k) for k in range(1, w + 1))
        reads = " + ".join("v%d" % ((k % w) + 1) for k in range(READS_PER_ITER))
        out.append(FN_SLOTTED.format(w=w, decls=decls, reads=reads))
        out.append(FN_UNSLOTTED.format(w=w, decls=decls, reads=reads))
    tail = TAIL.replace("__WIDTHS__", ", ".join(str(w) for w in WIDTHS))
    tail = tail.replace("__SLOTFNS__", ", ".join("c_slotted_%d" % w for w in WIDTHS))
    tail = tail.replace("__UNSLOTFNS__", ", ".join("c_unslotted_%d" % w for w in WIDTHS))
    tail = tail.replace("__READS__", str(READS_PER_ITER))
    out.append(tail)
    open(sys.argv[1], "w").write("".join(out))
    print("wrote", sys.argv[1], "with", len(WIDTHS), "width pairs,",
          READS_PER_ITER, "reads/iter")


if __name__ == "__main__":
    main()
