#!/usr/bin/env python3
"""Generate the per-BIF cross-engine bench (roadmap Part 1 Step 1, H1).

One function per case with the BIF call INLINE in its own loop. The first
attempt dispatched each case through a closure called per iteration; that added
a UDF frame (~550 ns on RustCFML, ~170 ns on Lucee) to every measurement, so a
~200 ns BIF became a small difference between two ~3,000 ns numbers AND the
frame-cost gap -- the very thing under test elsewhere -- leaked into the BIF
column. Inlining removes both problems.

Argument shapes are the measured means from the Step 0 census of a live warm
Preside render, not invented ones.
"""

# (name, fixture array, expression over `v`, calls per warm render)
CASES = [
    ("structKeyExists", "keyList",  "structKeyExists( fx.wideStruct, v ) ? 1 : 0", 2438),
    ("isNull",          "mixed",    "isNull( v ) ? 1 : 0",                          974),
    ("len_string",      "strs",     "len( v )",                                     568),
    ("len_array",       "smallArrs","len( v )",                                     320),
    ("isArray",         "mixed",    "isArray( v ) ? 1 : 0",                         746),
    ("isStruct",        "mixed",    "isStruct( v ) ? 1 : 0",                        597),
    ("trim",            "padded",   "len( trim( v ) )",                             463),
    ("isBoolean",       "bools",    "isBoolean( v ) ? 1 : 0",                       330),
    ("isNumeric",       "nums",     "isNumeric( v ) ? 1 : 0",                       222),
    ("reFind",          "subjects", "reFind( 'segment-[0-9]+', v )",                178),
    ("arrayFindNoCase", "smallArrs","arrayFindNoCase( v, 'BETA' )",                 135),
    ("structNew",       "nums",     "structCount( structNew() ) + v",               124),
    ("arrayLen",        "smallArrs","arrayLen( v )",                                120),
    ("lCase",           "longStrs", "len( lCase( v ) )",                            101),
    ("reFindNoCase",    "subjects", "reFindNoCase( 'SEGMENT-[0-9]+', v )",           74),
    ("isSimpleValue",   "mixed",    "isSimpleValue( v ) ? 1 : 0",                    65),
    ("listFirst",       "smallLists","len( listFirst( v ) )",                        60),
    ("listLen",         "smallLists","listLen( v )",                                 51),
    # structAppend is called as a STATEMENT, not folded into the sink: Lucee
    # returns a boolean from it and RustCFML returns the struct, so any
    # expression over the result is unportable (a real divergence, logged
    # separately). The struct mutation is the side effect neither engine can
    # eliminate. Target starts at 49 keys and stabilises at 80 after the first
    # append -- census arg1 mean is 77.9 keys -- so it does not grow.
    ("structAppend",    "nums",     "STMT:structAppend( fx.appendTarget, fx.appendSrc, true )", 51),
    ("structFind",      "keyList",  "structFind( fx.wideStruct, v )",                45),
    ("structIsEmpty",   "nums",     "( structIsEmpty( fx.wideStruct ) ? 1 : 0 ) + v",45),
    ("left",            "strs",     "len( left( v, 12 ) )",                          41),
    ("reReplace",       "subjects", "len( reReplace( v, '[0-9]+', 'N', 'all' ) )",    41),
    ("listFindNoCase",  "keyList",  "listFindNoCase( fx.bigList, v )",               38),
    ("listRest",        "smallLists","len( listRest( v ) )",                         37),
    ("replace",         "subjects", "len( replace( v, 'segment', 'SEG', 'all' ) )",   30),
    ("val",             "nums",     "val( v )",                                      25),
    ("hash",            "hashStrs", "len( hash( v ) )",                              23),
]

HEAD = r'''<cfsetting showdebugoutput="false">
<cfscript>
/*
 * GENERATED by scripts/perf/gen_bifbench.py -- edit the generator, not this file.
 *
 * Per-BIF cross-engine benchmark: PERFORMANCE_ROADMAP Part 1 Step 1, testing H1
 * ("individual BIF bodies are slower than Lucee's", ~1.6 ms of the 11.4 ms gap).
 *
 * Every argument shape is the measured mean from the Step 0 census of a LIVE
 * warm Preside render (8,343 BIF calls, 73 distinct builtins). Benching len()
 * with a 3-char literal when the workload passes 53-char strings is how a
 * microbench lies -- the rule that cost a build: a microbench put the BIF
 * intercept chain at 44% of a call, live Preside said 6.8%.
 *
 * Method, each point load-bearing:
 *  - One function per case with the BIF INLINE in its own loop. Dispatching
 *    cases through a per-iteration closure added a UDF frame to every sample
 *    and leaked the frame-cost gap into the BIF column.
 *  - Every result folds into an accumulator that is returned and printed:
 *    HotSpot deletes a loop whose result is unused and a constant-arg BIF then
 *    measures 0.000 ns.
 *  - Arguments vary per iteration from a 64-element fixture, so neither engine
 *    can hoist the call or serve it from a one-entry cache.
 *  - `__baseline` runs the identical loop and the identical fixture index with
 *    no BIF call; every case is reported net of it.
 *  - MINIMUM over the timed passes after N warmups: the least
 *    noise-contaminated estimate of a repeated deterministic operation.
 */
function buildFixtures() {
    var fx = {};
    var i  = 0;
    fx.wideStruct = structNew();                       // census: mean 49.1 keys
    for ( i = 1; i <= 49; i++ ) { fx.wideStruct[ "memberKeyNumber" & i ] = i; }
    fx.appendSrc = structNew();                        // census: arg2 mean 30.8 keys
    for ( i = 1; i <= 31; i++ ) { fx.appendSrc[ "srcKey" & i ] = i; }
    fx.appendTarget = structNew();                     // census: arg1 mean 77.9 keys
    for ( i = 1; i <= 49; i++ ) { fx.appendTarget[ "memberKeyNumber" & i ] = i; }

    fx.keyList = [];        // structKeyExists arg2: string, mean 24.8 chars
    fx.strs = [];           // len arg1 string arm: mean 52.9 chars
    fx.padded = [];         // trim arg1: mean 28.6 chars, padded
    fx.longStrs = [];       // lCase arg1: mean 198.9 chars
    fx.hashStrs = [];       // hash arg1: mean 552.5 chars
    fx.smallArrs = [];      // arrayLen/len array arm: mean 1.0-1.7 elements
    fx.mixed = [];          // isNull/isArray/isStruct see a MIXED type stream
    fx.bools = [];          // isBoolean: 81% real boolean, 18% string
    fx.nums = [];           // isNumeric: 100% int
    fx.subjects = [];       // reFind subject: mean 35.1 chars
    fx.smallLists = [];     // listFirst/listLen/listRest: mean ~28 chars
    for ( i = 1; i <= 64; i++ ) {
        arrayAppend( fx.keyList,    "memberKeyNumber" & ( ( i % 49 ) + 1 ) );
        arrayAppend( fx.strs,       repeatString( "ab7Xz ", 9 ) & i );
        arrayAppend( fx.padded,     "   " & repeatString( "qw", 12 ) & i & "  " );
        arrayAppend( fx.longStrs,   repeatString( "MixedCaseText", 15 ) & i );
        arrayAppend( fx.hashStrs,   repeatString( "abcdefghij", 55 ) & i );
        arrayAppend( fx.smallArrs,  [ "alpha" & i, "beta" & i ] );
        arrayAppend( fx.bools,      ( i % 5 ) == 0 ? "true" : ( ( i % 3 ) == 0 ) );
        arrayAppend( fx.nums,       i );
        arrayAppend( fx.subjects,   "prefix/segment-" & i & "/tail/value-part" );
        arrayAppend( fx.smallLists, "one" & i & ",two,three,four,five" );
        switch ( i % 8 ) {
            case 0:  arrayAppend( fx.mixed, true );                  break;
            case 1:  arrayAppend( fx.mixed, i );                     break;
            case 2:  arrayAppend( fx.mixed, "someStringValue" & i ); break;
            case 3:  arrayAppend( fx.mixed, [ 1, 2, i ] );           break;
            case 4:  arrayAppend( fx.mixed, { a = i, b = "x" } );    break;
            case 5:  arrayAppend( fx.mixed, "another" & i );         break;
            case 6:  arrayAppend( fx.mixed, false );                 break;
            default: arrayAppend( fx.mixed, "third" & i );           break;
        }
    }
    fx.bigList = "";                                   // listFindNoCase: mean 549.4 chars
    for ( i = 1; i <= 60; i++ ) { fx.bigList = listAppend( fx.bigList, "memberKeyNumber" & i ); }
    return fx;
}

// The baseline: same loop, same fixture index, no BIF. Subtracted from every
// case, so what remains is the builtin call and its body.
function c__baseline( n, fx ) {
    var acc = 0;
    var v   = 0;
    for ( var i = 0; i < n; i++ ) { v = fx.mixed[ ( i % 64 ) + 1 ]; acc += 1; }
    return acc;
}
'''

FN = '''
function c_{ident}( n, fx ) {{
    var acc = 0;
    var v   = 0;
    for ( var i = 0; i < n; i++ ) {{ v = fx.{arr}[ ( i % 64 ) + 1 ]; acc += {expr}; }}
    return acc;
}}
'''

FN_STMT = '''
function c_{ident}( n, fx ) {{
    var acc = 0;
    var v   = 0;
    for ( var i = 0; i < n; i++ ) {{ v = fx.{arr}[ ( i % 64 ) + 1 ]; {expr}; acc += 1; }}
    return acc;
}}
'''

TAIL = r'''
// Dispatch by first-class function reference, not `invoke( "", ... )`: the
// empty-component form is not portable (RustCFML raises "Component '' not
// found"), and a reference costs one call per PASS, not per iteration.
function timeCase( fn, n, fx, warmups, passes ) {
    var best = 0;
    var acc  = 0;
    for ( var p = 1; p <= warmups + passes; p++ ) {
        var t0 = getTickCount( "nano" );
        acc += fn( n, fx );
        var el = getTickCount( "nano" ) - t0;
        if ( p > warmups && ( best == 0 || el < best ) ) { best = el; }
    }
    return { ns = best / n, acc = acc };
}

iters   = val( url.iters   ?: 200000 );
passes  = val( url.passes  ?: 5 );
warmups = val( url.warmups ?: 3 );
fixtures = buildFixtures();
sink = 0;

baseRes = timeCase( c__baseline, iters, fixtures, warmups, passes );
sink   += baseRes.acc;
base    = baseRes.ns;

names = [ __NAMES__ ];
fns   = [ __FNS__ ];
calls = [ __CALLS__ ];

writeOutput( "PORT=" & cgi.server_port & chr(10) );
writeOutput( "ENGINE=" & server.coldfusion.productname & " " & server.coldfusion.productversion & chr(10) );
writeOutput( "ITERS=" & iters & " PASSES=" & passes & " WARMUPS=" & warmups & chr(10) );
writeOutput( "BASELINE_NS=" & numberFormat( base, "0.000" ) & chr(10) );
writeOutput( "NAME" & chr(9) & "NS_PER_CALL" & chr(9) & "CALLS_PER_RENDER" & chr(9) & "MS_PER_RENDER" & chr(10) );
for ( ci = 1; ci <= arrayLen( names ); ci++ ) {
    r    = timeCase( fns[ ci ], iters, fixtures, warmups, passes );
    sink += r.acc;
    net  = max( r.ns - base, 0 );
    writeOutput( names[ ci ] & chr(9) & numberFormat( net, "0.000" )
               & chr(9) & calls[ ci ]
               & chr(9) & numberFormat( net * calls[ ci ] / 1000000, "0.0000" ) & chr(10) );
}
writeOutput( "SINK=" & sink & chr(10) );
</cfscript>
'''

out = [HEAD]
for name, arr, expr, calls in CASES:
    if expr.startswith("STMT:"):
        out.append(FN_STMT.format(ident=name, arr=arr, expr=expr[5:]))
    else:
        out.append(FN.format(ident=name, arr=arr, expr=expr))
tail = TAIL.replace("__NAMES__", ", ".join('"%s"' % c[0] for c in CASES))
tail = tail.replace("__FNS__", ", ".join("c_%s" % c[0] for c in CASES))
tail = tail.replace("__CALLS__", ", ".join(str(c[3]) for c in CASES))
out.append(tail)

import sys
open(sys.argv[1], "w").write("".join(out))
print("wrote", sys.argv[1], "with", len(CASES), "cases")
