#!/usr/bin/env python3
"""Generate the per-OPERATION cross-engine bench (roadmap Part 1 Step 2, H2).

H2: "per-op interpreter cost is uniformly worse than Lucee's JIT'd bytecode."
~213,966 ops/request at ~98 ns/op. If our per-op cost is ~2x theirs across the
board, that IS the gap and no call-path shaving touches it.

Lucee has no "op" granularity, so this proxies: minimal CFML fragments each
isolating ONE language operation in a loop, per-iteration cost on both engines
net of an empty loop of the same shape.

The reconciliation is the point, not the individual numbers: sum(op_count x
op_cost) must land within ~20% of the measured ~21 ms render. If it does not,
the model is wrong and THAT is the finding.

Same method rules as the BIF bench: results fold into a returned accumulator
(HotSpot deletes a loop whose result is unused), operands vary per iteration,
minimum over timed passes after warmups, one function per case with the
operation inline (no per-iteration closure).
"""

# (name, setup lines, loop body, ops-per-iteration note)
CASES = [
    ("empty",
     [],
     "acc += 1;",
     "loop increment + compare + jump + sink add"),

    ("local_read",
     ["var src = 7;"],
     "acc += src;",
     "one LoadLocal/LoadSlot over the empty loop"),

    ("local_write",
     ["var dst = 0;"],
     "dst = i; acc += 1;",
     "one StoreLocal/StoreSlot"),

    ("int_add",
     ["var a = 3; var b = 4;"],
     "acc += a + b;",
     "one Add over two local reads"),

    ("int_compare",
     ["var a = 3;"],
     "acc += ( a < i ) ? 1 : 0;",
     "one Lt + branch"),

    ("branch",
     [],
     "if ( ( i % 2 ) == 0 ) { acc += 1; } else { acc += 2; }",
     "Mod + Eq + JumpIfFalse + Jump"),

    ("string_literal",
     ["var s = '';"],
     "s = 'someLiteralValue'; acc += 1;",
     "one String op + store"),

    ("string_concat",
     ["var a = 'alpha'; var b = 'beta'; var s = '';"],
     "s = a & b; acc += 1;",
     "one Concat over two reads"),

    ("struct_read",
     ["var st = { alpha = 1, beta = 2, gamma = 3 };"],
     "acc += st.beta;",
     "one GetProperty"),

    ("struct_write",
     ["var st = { alpha = 1, beta = 2, gamma = 3 };"],
     "st.beta = i; acc += 1;",
     "one SetProperty"),

    ("struct_read_wide",
     ["var st = {}; for ( var w = 1; w <= 49; w++ ) { st[ 'memberKeyNumber' & w ] = w; }"],
     "acc += st.memberKeyNumber37;",
     "GetProperty on a census-width (49-key) struct"),

    ("array_read",
     ["var arr = []; for ( var w = 1; w <= 64; w++ ) { arrayAppend( arr, w ); }"],
     "acc += arr[ ( i % 64 ) + 1 ];",
     "one GetIndex (plus the Mod the baseline lacks)"),

    ("array_write",
     ["var arr = []; for ( var w = 1; w <= 64; w++ ) { arrayAppend( arr, w ); }"],
     "arr[ ( i % 64 ) + 1 ] = i; acc += 1;",
     "one SetIndex"),

    ("global_read",
     [],
     "acc += pageLevelCounter;",
     "one LoadGlobal (page scope, not local)"),

    ("udf_call_0",
     [],
     "acc += emptyFn0();",
     "one Call + Return, no arguments"),

    ("udf_call_2",
     [],
     "acc += emptyFn2( i, 1 );",
     "one Call + Return with 2 positional arguments"),

    ("cfc_method_call",
     ["var obj = fx.obj;"],
     "acc += obj.ping();",
     "one CallMethod on a component instance"),

    ("cfc_property_read",
     ["var obj = fx.obj;"],
     "acc += obj.counter;",
     "one GetProperty on a component instance"),
]

HEAD = r'''<cfsetting showdebugoutput="false">
<cfscript>
/*
 * GENERATED by scripts/perf/gen_opbench.py -- edit the generator, not this file.
 *
 * Per-OPERATION cross-engine benchmark: PERFORMANCE_ROADMAP Part 1 Step 2 (H2,
 * "per-op interpreter cost is uniformly worse than Lucee's JIT'd bytecode").
 *
 * Each case isolates one language operation in its own inline loop; every case
 * is reported net of `empty`, which is the same loop with only the sink add.
 * Results fold into a returned accumulator so neither engine can delete the
 * loop, and the reported figure is the MINIMUM over the timed passes.
 *
 * URL params: ?iters=N &passes=N &warmups=N
 */
pageLevelCounter = 3;

function emptyFn0() { return 1; }
function emptyFn2( a, b ) { return 1; }

function buildFixtures() {
    var fx = {};
    fx.obj = new Pinger();
    return fx;
}
'''

FN = '''
function c_{ident}( n, fx ) {{
    var acc = 0;
    {setup}
    for ( var i = 0; i < n; i++ ) {{ {body} }}
    return acc;
}}
'''

TAIL = r'''
function timeCase( fn, n, fx, warmups, passes ) {
    var best = 0;
    var acc  = 0;
    for ( var p = 1; p <= warmups + passes; p++ ) {
        var t0 = getTickCount( "nano" );
        acc += fn( n, fx );
        var el = getTickCount( "nano" ) - t0;
        if ( p > warmups && ( best == 0 || el < best ) ) { best = el; }
    }
    return { ns = best / n, acc = acc };
}

iters   = val( url.iters   ?: 500000 );
passes  = val( url.passes  ?: 5 );
warmups = val( url.warmups ?: 3 );
fixtures = buildFixtures();
sink = 0;

// The baseline is measured FIRST and AGAIN LAST, and the minimum is used.
// Measured only first, it pays Lucee's class-load + JIT warm-up before HotSpot
// has seen the shape, and comes out HIGHER than every case it is meant to be
// subtracted from -- which clamped all 18 Lucee cases to 0.000.
baseFirst = timeCase( c_empty, iters, fixtures, warmups, passes );
sink     += baseFirst.acc;

names = [ __NAMES__ ];
fns   = [ __FNS__ ];

results = [];
for ( ci = 1; ci <= arrayLen( names ); ci++ ) {
    if ( names[ ci ] == "empty" ) { continue; }
    r     = timeCase( fns[ ci ], iters, fixtures, warmups, passes );
    sink += r.acc;
    arrayAppend( results, { name = names[ ci ], ns = r.ns } );
}
baseLast = timeCase( c_empty, iters, fixtures, warmups, passes );
sink    += baseLast.acc;
base     = min( baseFirst.ns, baseLast.ns );

writeOutput( "PORT=" & cgi.server_port & chr(10) );
writeOutput( "ITERS=" & iters & " PASSES=" & passes & " WARMUPS=" & warmups & chr(10) );
writeOutput( "BASELINE_NS=" & numberFormat( base, "0.000" ) & chr(10) );
writeOutput( "BASELINE_FIRST=" & numberFormat( baseFirst.ns, "0.000" )
           & " BASELINE_LAST=" & numberFormat( baseLast.ns, "0.000" ) & chr(10) );
writeOutput( "NAME" & chr(9) & "NS_PER_ITER" & chr(9) & "NS_NET" & chr(10) );
writeOutput( "empty" & chr(9) & numberFormat( base, "0.000" ) & chr(9) & "0.000" & chr(10) );
for ( ri = 1; ri <= arrayLen( results ); ri++ ) {
    net = max( results[ ri ].ns - base, 0 );
    writeOutput( results[ ri ].name & chr(9) & numberFormat( results[ ri ].ns, "0.000" )
               & chr(9) & numberFormat( net, "0.000" ) & chr(10) );
}
writeOutput( "SINK=" & sink & chr(10) );
</cfscript>
'''

PINGER = '''/**
 * Minimal component for the CallMethod / instance-property cases. Kept
 * deliberately tiny: the census found the site's 5,367 instances average
 * 2.3 data members, so a fat fixture would not be representative.
 */
component {
    variables.counter = 1;
    this.counter      = 1;
    public numeric function ping() { return 1; }
}
'''


def main():
    import sys
    out = [HEAD]
    for name, setup, body, _ in CASES:
        out.append(FN.format(ident=name, setup="\n    ".join(setup), body=body))
    tail = TAIL.replace("__NAMES__", ", ".join('"%s"' % c[0] for c in CASES))
    tail = tail.replace("__FNS__", ", ".join("c_%s" % c[0] for c in CASES))
    out.append(tail)
    target = sys.argv[1]
    open(target, "w").write("".join(out))
    import os
    open(os.path.join(os.path.dirname(target), "Pinger.cfc"), "w").write(PINGER)
    print("wrote", target, "with", len(CASES), "cases + Pinger.cfc")


if __name__ == "__main__":
    main()
